
import javax.swing.JOptionPane;
import codigo.Rellenar;
import Conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author coron
 */
public class Principal extends javax.swing.JFrame {

    //private Cliente_formulario cf;
      conexion con = new conexion();
     Connection conect;
    int cambio;
    Rellenar a = new Rellenar();
    public Principal() {
        initComponents();
        this.conect = con.conectar();
        a.rellenar("mes","mes", mes);
        a.rellenar("semana","semana", semana);
        tabla();
    }

    

public void tabla() {
    // Definir las columnas de la tabla
    String[] columnNames = {"Semana", "Días", "Puntos de Venta", "Total Inicial"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0); // Modelo para la tabla

    // Consulta SQL
    String query = "SELECT r.semana, COUNT(DISTINCT r.fecha) AS dias, " +
                   "SUM(r.puntos_venta_inicial) AS puntos_venta, " +
                   "SUM(r.total_inicial) AS total_inicial " +
                   "FROM registro r " +
                   "LEFT JOIN semanas s ON r.semana = s.numero_semana " +
                   "GROUP BY r.semana " + // Agrupamos solo por semana
                   "ORDER BY r.semana";

    try {
        Statement stmt = conect.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        // Limpiar el modelo existente antes de agregar nuevas filas
        model.setRowCount(0);

        while (rs.next()) {
            String semana = rs.getString("semana");
            int dias = rs.getInt("dias");
            int puntosVenta = rs.getInt("puntos_venta");
            float totalInicial = rs.getFloat("total_inicial");

            // Agregar fila al modelo
            model.addRow(new Object[]{semana, dias, puntosVenta, totalInicial});
        }

        // Asignar el modelo a la tabla llamada 'datos'
        Datos.setModel(model); // Asegúrate de que 'datos' sea el nombre correcto del JTable

        // Opcional: Ajustar tamaño de columnas
        Datos.getColumnModel().getColumn(0).setPreferredWidth(100); // Semana
        Datos.getColumnModel().getColumn(1).setPreferredWidth(50);  // Días
        Datos.getColumnModel().getColumn(2).setPreferredWidth(100); // Puntos de Venta
        Datos.getColumnModel().getColumn(3).setPreferredWidth(100); // Total Inicial

    } catch (SQLException e) {
        e.printStackTrace(); // Manejo de errores
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        jMenuItem4 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        Datos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mes = new javax.swing.JComboBox<>();
        semana = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Mes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        item_agregar_cliente = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jLabel4.setText("Semana: ");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Semanas", "Puntos de Venta", "Cantidad de dias ", "Total"
            }
        ));
        jScrollPane1.setViewportView(Datos);

        jLabel1.setText("Total general:");

        jLabel2.setText("Objetivo");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel3.setText("Mes:        ");

        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });

        jLabel5.setText("Mes:");

        jLabel6.setText("Semana:");

        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Nuevo");

        Mes.setText("Mes");
        Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesActionPerformed(evt);
            }
        });
        jMenu1.add(Mes);

        jMenuItem2.setText("Semana");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Dia");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Fiado");

        jMenuItem5.setText("Cliente Fiado");
        jMenuItem5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jMenuItem5KeyTyped(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Opciones ");

        jMenu6.setText("Eliminar");
        jMenu7.add(jMenu6);

        jMenu5.setText("Modificar");
        jMenu7.add(jMenu5);

        jMenuItem3.setText("Ver");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Clientes");

        item_agregar_cliente.setText("Gestionar");
        item_agregar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_agregar_clienteActionPerformed(evt);
            }
        });
        jMenu8.add(item_agregar_cliente);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jTextField5))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jTextField3))
                        .addGap(26, 26, 26)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(semana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int res = JOptionPane.showConfirmDialog(null,"Esta por ingresar un nuevo dia. ¿Desea continuar?","Advertencia", JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION){
        Dias a = new Dias();
       a.setVisible(true);
       dispose();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       int res = JOptionPane.showConfirmDialog(null,"Esta por ingresar una nueva semana. ¿Desea continuar?","Advertencia", JOptionPane.YES_NO_OPTION);
       if(res==JOptionPane.YES_OPTION){
        Formulario a = new Formulario();
        a.setVisible(true);
        dispose();
       }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesActionPerformed
        // TODO add your handling code here:
        // Mostrar el cuadro de diálogo con dos opciones
    int respuesta = JOptionPane.showConfirmDialog(null, "Está por ingresar un nuevo mes. ¿Desea continuar?", "Advertencia", JOptionPane.YES_NO_OPTION);
    
    // Si el usuario elige "Sí" (YES_OPTION), continúa con la acción
    if (respuesta == JOptionPane.YES_OPTION) {
        mes a = new mes();
        a.setVisible(true);
        dispose(); // Cierra la ventana actual
    }
    }//GEN-LAST:event_MesActionPerformed

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Ver_datos a = new Ver_datos();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void item_agregar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_agregar_clienteActionPerformed
        Cliente_formulario cf = new Cliente_formulario();
        cf.setVisible(true);
    }//GEN-LAST:event_item_agregar_clienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String mesSeleccionado = mes.getSelectedItem().toString();
    String semanaSeleccionada = semana.getSelectedItem().toString();
     System.out.println("Mes seleccionado: " + mesSeleccionado);
    System.out.println("Semana seleccionada: " + semanaSeleccionada);
    // Llamar al método para llenar la tabla con los datos filtrados
    llenarTablaFiltrada(mesSeleccionado, semanaSeleccionada);
    }//GEN-LAST:event_jButton1ActionPerformed
private void jMenuItem5ActionPerformed(java.awt.event.KeyEvent evt) {                                    
        // TODO add your handling code here:
        cliente_fiado a = new cliente_fiado();
        a.setVisible(true);
    }  
    private void jMenuItem5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem5KeyTyped
       
    }//GEN-LAST:event_jMenuItem5KeyTyped
public void llenarTablaFiltrada(String mes, String semana) {
    // Definir las columnas de la tabla
    String[] columnNames = {"Semana", "Días", "Puntos de Venta", "Total Inicial"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0); // Modelo para la tabla

    // Consulta SQL para filtrar por mes y semana
    String query = "SELECT r.semana, COUNT(DISTINCT r.fecha) AS dias, " +
                   "SUM(r.puntos_venta_inicial) AS puntos_venta, " +
                   "SUM(r.total_inicial) AS total_inicial " +
                   "FROM registro r " +
                   "LEFT JOIN semanas s ON r.semana = s.numero_semana " +
                   "WHERE s.mes = ? AND r.semana = ? " + // Filtramos por mes y semana
                   "GROUP BY r.semana " +
                   "ORDER BY r.semana";

    try {
        PreparedStatement pstmt = conect.prepareStatement(query);
        pstmt.setString(1, mes); // Establecer el mes seleccionado
        pstmt.setString(2, semana); // Establecer la semana seleccionada
        
        ResultSet rs = pstmt.executeQuery();

        // Limpiar el modelo existente antes de agregar nuevas filas
        model.setRowCount(0);

        // Verificar si hay resultados
        if (!rs.isBeforeFirst()) { // Verifica si el ResultSet está vacío
            model.addRow(new Object[]{"No se encuentran datos", "", "", ""}); // Agrega el mensaje
        } else {
            while (rs.next()) {
                String semanaNombre = rs.getString("semana");
                int dias = rs.getInt("dias");
                int puntosVenta = rs.getInt("puntos_venta");
                float totalInicial = rs.getFloat("total_inicial");

                // Agregar fila al modelo
                model.addRow(new Object[]{semanaNombre, dias, puntosVenta, totalInicial});
            }
        }

        // Asignar el modelo a la tabla llamada 'datos'
        Datos.setModel(model); // Asegúrate de que 'datos' sea el nombre correcto del JTable

        // Opcional: Ajustar tamaño de columnas
        Datos.getColumnModel().getColumn(0).setPreferredWidth(100); // Semana
        Datos.getColumnModel().getColumn(1).setPreferredWidth(50);  // Días
        Datos.getColumnModel().getColumn(2).setPreferredWidth(100); // Puntos de Venta
        Datos.getColumnModel().getColumn(3).setPreferredWidth(100); // Total Inicial

    } catch (SQLException e) {
        e.printStackTrace(); // Manejo de errores
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Datos;
    private javax.swing.JMenuItem Mes;
    private javax.swing.JMenuItem item_agregar_cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> mes;
    private javax.swing.JComboBox<String> semana;
    // End of variables declaration//GEN-END:variables
}
